### ISSUE TITLE
[ios] Dropping a PNG will give a PNG path but JPEG content

### ISSUE THREAD

**Issue by moffatman** [alexrabin/FlutterNativeDragAndDrop#12]
See below method, the `ext` is taken from the userImageUrl, but the content is always image.jpegData. Ideally we can get the image data in original format without conversion, but if not at least the extension should be correctly set to JPEG.
 https://github.com/alexrabin/FlutterNativeDragAndDrop/blob/4d86121734ca0057e611bee58aad1f8d73f96b77/ios/Classes/SwiftNativeDragNDropPlugin.swift#L582

**Comment by alexrabin** [comment]
Good find! When I have a moment I'll look into this more.

**Comment by alexrabin** [comment]
@moffatman please take a look at pull request #13 at your earliest connivence.

**Comment by moffatman** [comment]
Looks ok 👍

**Comment by alexrabin** [comment]
@moffatman Merged into main. Test out version 0.0.5, let me know if it works

**Comment by moffatman** [comment]
Yep, problem is resolved in 0.0.5. Thanks for the quick fix 😁

**Comment by alexrabin** [comment]
No problem 👍
