### ISSUE TITLE
Some file types (apk) can't be dropped from Files' iCloud

### ISSUE THREAD

**Issue by getBoolean** [alexrabin/FlutterNativeDragAndDrop#2]
I've run into the issue while testing that some filetypes can't be dropped from iCloud in the Files app, specifically apk. It works fine using Dropbox. This may not be limited to just apk files, I suspect its something related to iOS' Uniform Type Identifier system.

I'm not entirely sure of the reason, but theres two issues I've found related to iCloud. If DropDataType.file is enabled, apks cannot be dropped from iCloud unless "apk" is added to allowed file extensions. A second issue is that even when "apk" is added to the file extensions and it looks like it should accept, it does not load the file if dragged from iCloud.

In the first gif, you can see that the apk cannot be uploaded if it is on the iCloud drive, while it can if it is stored locally.

![image](https://user-images.githubusercontent.com/19920697/150672993-88f8f4fb-eb17-4535-b9d7-fa5015f66b95.gif)

This second gif shows that other files work fine through iCloud

![image](https://user-images.githubusercontent.com/19920697/150673026-f4be43ff-df0d-4788-b953-99adb3602a01.gif)

**Comment by alexrabin** [comment]
Looking into it. Unknown if this https://developer.apple.com/forums/thread/90204 has anything to do with it

**Comment by alexrabin** [comment]
Possible error this line didn’t get merged correctly. The file dataType is missing. https://github.com/alexrabin/FlutterNativeDragAndDrop/blob/ef64510a527e17d15318a4f805b58fa12392517e/lib/src/drop_data.dart#L3

**Comment by getBoolean** [comment]
I think the problem is that the UTI given by iCloud for APKs is not a subtype of kUTTypeData, but it is when dropped from local storage and Dropbox. I just tested it and it worked when replacing kUTTypeData with kUTTypeItem. It's worth noting kUTTypeItem will also allow Directories to be dropped.

Item https://web.archive.org/web/20190621082935/https://developer.apple.com/documentation/mobilecoreservices/uttype/uti_abstract_types

Data https://web.archive.org/web/20190621082952/https://developer.apple.com/documentation/mobilecoreservices/uttype/uti_concrete_types

**Comment by alexrabin** [comment]
I guess we can add the option to allow directories to be dragged and dropped to fix this?

**Comment by alexrabin** [comment]
Looking at this too:  https://stackoverflow.com/questions/37296929/implement-document-picker-in-swift-ios/47948581 maybe enabling iCloud will help?

**Comment by alexrabin** [comment]
> I think the problem is that the UTI given by iCloud for APKs is not a subtype of kUTTypeData, but it is when dropped from local storage and Dropbox. I just tested it and it worked when replacing kUTTypeData with kUTTypeItem. It's worth noting kUTTypeItem will also allow Directories to be dropped.
> 
> 
> 
> Item https://web.archive.org/web/20190621082935/https://developer.apple.com/documentation/mobilecoreservices/uttype/uti_abstract_types
> 
> 
> 
> Data https://web.archive.org/web/20190621082952/https://developer.apple.com/documentation/mobilecoreservices/uttype/uti_concrete_types

What I can do is add an option to detect the kuttypeitem in the perform drop method but in the can drop method only check for the actual file type so it won't allow directories

**Comment by alexrabin** [comment]
I was able to get iCloud apk file to work when you add apk has a custom extension. When you just have the DropDataType.file with no extension the iCloud apk doesn't register that it can be dropped

**Comment by alexrabin** [comment]
@getBoolean I published v0.0.3 with a fix. Just specify the extension and you should be good to go.
