### ISSUE TITLE
Able To Drop Non Allowed Items

### ISSUE THREAD

**Issue by getBoolean** [alexrabin/FlutterNativeDragAndDrop#4]
Problem:
It is possible to drop items that have not been allowed as long as one item in the drop session is allowed

![image](https://user-images.githubusercontent.com/19920697/150723456-cae9825a-4fed-4efa-99f3-86f8c1208515.gif)

Proposed solution:
In the handle drop method, check the item if it conforms to an allowed type identifier or file extension. Code from the can drop method should be pulled into private functions so it can be reused (if possible).

**Comment by getBoolean** [comment]
I can begin work on this if thats okay with you.

**Comment by alexrabin** [comment]
I think this could work as long as there is a boolean like `allowOtherItemsToo`. That's an extremely bad example but you know what I mean. There should be an option to allow it basically

**Comment by getBoolean** [comment]
So just to make sure I understand you correctly.

The programmer should be able to set `receiveOnlyAllowedItems` to false. The default would be true.

For the docs for it, it says
```
Receive all dropped items if at least one item in the dropping session is:
  an allowed [DropDataType], or is a file with the file extension included in `allowedFileExtensions`
```

Is this what you are thinking?

**Comment by getBoolean** [comment]
So just to make sure I understand you correctly.

The programmer should be able to set `receiveOnlyAllowedItems` to false. The default would be true.

For the docs for it, it says
```
Receive only the dropped items that are allowed by `allowedDropDataTypes` or `allowedDropFileExtensions`.

Disabling this to receive all dropped items if at least one item is allowed.
```

Is this what you are thinking?

**Comment by alexrabin** [comment]
Sounds perfect. I don't really see the use case for this but whatever makes you happy 😆 Thanks for all your hard work!

**Comment by getBoolean** [comment]
I thought that it was weird that files that weren't allowed would be copied to the app directory as long as one file dropped is allowed. This would prevent that from happening and maybe save storage space if the files are big.

On that topic, are files copied to a permanent location or temporary? We should probably put that somewhere in the docs

**Comment by alexrabin** [comment]
> I thought that it was weird that files that weren't allowed would be copied to the app directory as long as one file dropped is allowed. This would prevent that from happening and maybe save storage space if the files are big.

Yeah that's a bug and definitely not the intended behavior. This needs to be fixed immediately.

> On that topic, are files copied to a permanent location or temporary? We should probably put that somewhere in the docs

Right now all files are copied to the temp folder. In the next version I'll mention it in the readme

**Comment by getBoolean** [comment]
Do you still want that behind a boolean flag? I'm not seeing a use case for it so it's probably not needed.

**Comment by alexrabin** [comment]
Yeah that boolean flag is not needed at all

**Comment by alexrabin** [comment]
> On that topic, are files copied to a permanent location or temporary? We should probably put that somewhere in the docs

There is a function in the swift code to remove all cached files. I initially had the function being called every time a NativeDropView was initiated. The problem with that is if you added a file and then left a page and then went to a new page with a NativeDropView, the cached files would be cleared and that added file you had earlier would no longer exist. So I think to remove the cached files we just need to add a method handler so the programmer can decide when to remove the cached files like this one: https://github.com/alexrabin/FlutterNativeDragAndDrop/blob/e76a20ef59e89724de697cff0d63511ee255abd5/ios/Classes/SwiftNativeDragNDropPlugin.swift#L94

but instead of it being in the DropView class it needs to be in this class:
https://github.com/alexrabin/FlutterNativeDragAndDrop/blob/e76a20ef59e89724de697cff0d63511ee255abd5/ios/Classes/SwiftNativeDragNDropPlugin.swift#L11

This is a completely separate issue though.

**Comment by alexrabin** [comment]
Part of the problem is the [hasitemsconforming](https://developer.apple.com/documentation/uikit/uidragdropsession/2891006-hasitemsconforming) says 
> Returns a Boolean value that indicates whether **at least one drag item** in the session conforms to at least one of the specified UTIs.

So we are going to need to find a better way around this.

**Comment by alexrabin** [comment]
What we can do is perform a loop on all the incoming identifiers and see if they are in allowed type identifiers. If one of the identifiers failed then it would return false.

https://github.com/alexrabin/FlutterNativeDragAndDrop/blob/e76a20ef59e89724de697cff0d63511ee255abd5/ios/Classes/SwiftNativeDragNDropPlugin.swift#L407

I already have this function in the dropview

**Comment by getBoolean** [comment]
Working as intended
