### ISSUE TITLE
[Feature] Android Support

### ISSUE THREAD

**Issue by getBoolean** [alexrabin/FlutterNativeDragAndDrop#6]
This issue will track android support's overall development. Individual features may get split into its own issue. Research on APIs and their implementation should also be posted here.

## API

Android 7+

Android Drag and Drop API: https://developer.android.com/guide/topics/ui/drag-drop#DragPermissionsMultiWindow
Multi-Window guide: https://developer.android.com/guide/topics/large-screens/multi-window-support
Multi-Window/Multi-Instance: https://developer.samsung.com/galaxy-z/multi-window.html
DropHelper (min API level 24), simplified drag and drop: https://developer.android.com/guide/topics/ui/drag-drop#drophelper_for_simplified_drag_and_drop

Galaxy Fold, Z Fold2, or Z Fold3: https://developer.samsung.com/codelab/galaxy-z/multi-window-drag-drop.html
Emulator: https://developer.samsung.com/galaxy-z/testing.html

Surface Duo: https://docs.microsoft.com/en-us/dual-screen/android/sample-code/drag-drop?tabs=java
Emulator: https://docs.microsoft.com/en-us/dual-screen/android/emulator/surface-duo-download
Java SDK Examples: https://github.com/microsoft/surface-duo-sdk-samples
App Examples: https://github.com/microsoft/surface-duo-app-samples

## Permissions

The following permissions are required for drag and drop in different scenarios: ([info from here](https://developer.huawei.com/consumer/en/doc/90101#h1-1577442089219))

For public files, to use the media library `MediaProvier`, permissions for reading and writing external storage are required.

The `FileProvider` is used to share private app data. Use the per-URI permission mechanism for authorization. The source app can set `Intent.FLAG_GRANT_READ_URI_PERMISSION` or `Intent.FLAG_GRANT_WRITE_URI_PERMISSION` to grant the read or write permission to the `Intent` data or the `URI` specified in `ClipData`.

## Features

- [x] NativeDropView (Drop Items Into App)
- [ ] NativeDragView (Drag Items Outside App)
- [x] Allowed Data Types
- [x] Allowed File Extensions
- [x] Item Types
  - [x] text
  - [x] urls (`Patterns.WEB_URL.matcher(url).matches()`)
  - [x] images
  - [x] videos
  - [x] audio
  - [x] pdfs
  - [x] files
- [x] Change parameters during runtime

Other possible features
- [ ] Callback to update UI according to result of [drag events](https://developer.android.com/guide/topics/ui/drag-drop#AboutDragEvent). This is all conceptual, implementation has not been decided yet but the idea is that the UI should be able to react to drag events.
  - [ ] ACTION_DRAG_STARTED: Drag started. Includes can/cannot accept, x/y location, and description of drag contents.
  - [ ] ACTION_DRAG_ENTERED: Drag entered NativeDropView's bounds. Includes can/cannot accept, and description of drag contents.
  - [ ] ACTION_DRAG_LOCATION: Drag is in NativeDropView's bounds and not in a child view that can accept. Includes x/y location.
  - [ ] ACTION_DRAG_EXITED: Drag moved out of NativeDropView's bounds or into a child view that can accept. Includes description of drag contents.
  - [ ] ACTION_DROP: Dragged contents dropped on NativeDropView and can accept and not in a child view that can accept the drop. Includes x/y location, and description of drag contents.
  - [ ] ACTION_DRAG_ENDED: Drag and drop session concluded. Includes if data was received and the x/y location of the drop in the view.
- [ ] DraggableText (Tap and hold to drag entire text)
- [ ] DraggableSelectableText (Tap and hold to select text, then tap and hold on selected text to drag)
- [ ] DraggableImage

**Comment by getBoolean** [comment]
desktop_drop also has android support in preview https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/desktop_drop/android/src/main/kotlin/one/mixin/desktop/drop/DesktopDropPlugin.kt

It might be a good reference too

**Comment by alexrabin** [comment]
Android support is in the works and just needs further testing before it can be merged into main
