### ISSUE TITLE
Files from messages app sends url instead of image data

### ISSUE THREAD

**Issue by alexrabin** [alexrabin/FlutterNativeDragAndDrop#7]
A file path should transfer to a local path with data in the flutter app not copy over the file path

**Comment by alexrabin** [comment]
![image](https://user-images.githubusercontent.com/15949910/150923390-f6d4f021-4e88-4bc8-b35f-f7451ab537b1.gif)

**Comment by getBoolean** [comment]
It also does this for files from Filza (jailbreak app).

**Comment by alexrabin** [comment]
I think when a string is detected it should check if it starts with file:///var and then try and get the data from that file

**Comment by alexrabin** [comment]
Might need to check if a drop item is a uiimage to fix this https://www.appcoda.com/drag-and-drop/

**Comment by alexrabin** [comment]
I'm curious what happens when text is disabled in this scenario

**Comment by getBoolean** [comment]
> I think when a string is detected it should check if it starts with file:///var and then try and get the data from that file 

I believe there is a file url UTI, maybe we can test if it is that type

**Comment by getBoolean** [comment]
> I'm curious what happens when text is disabled in this scenario 

At least for images on web and files from Filza File Manager, when both URL and Text is disabled it sends as the image/file. If either url or text is enabled, it gets received as text

Edit: I've confirmed its the same for iMessage

**Comment by getBoolean** [comment]
> > I'm curious what happens when text is disabled in this scenario 
> 
> At least for images on web and files from Filza File Manager, when both URL and Text is disabled it sends as the image/file. If either url or text is enabled, it gets received as text
> 
> Edit: I've confirmed its the same for iMessage

We should be able to fix this by checking if its a URL second to last, then checking if its a plain text very last.


URL is also incorrectly given DropDataType.text instead of url

```dart

else if (d['url'] != null) {
  //add url
  var url = d['url'] as String;
  var dropData = DropData(type: DropDataType.text, dropText: url);
  dropDataList.add(dropData);
} 
```

Also, currently we are checking if text or url is allowed before performing the drop. We should not check that, we should only be checking for subtypes of files.

**Comment by alexrabin** [comment]
@getBoolean I fixed setting the url dropdatatype to url and switched around the url and Plain text to be the last ones. regarding your last comment, why shouldn't we check for text or url? If they only allow text or url why wouldn't we check for that?

**Comment by getBoolean** [comment]
> @getBoolean I fixed setting the url dropdatatype to url and switched around the url and Plain text to be the last ones. regarding your last comment, why shouldn't we check for text or url? If they only allow text or url why wouldn't we check for that?

We already have the is allowed boolean flag so we don't need to check again. Having those additional checks will mean it will won't be received when receive non allowed items is enabled.

I don't like it being sent as a text or url based on the position of the if else, maybe we can find a better solution for that. (Of course that's only the case if urls count as text to iOS, which idk)

**Comment by alexrabin** [comment]
Right now having the file, then url, and then the text check has fixed the image issue completely

**Comment by alexrabin** [comment]
I'll get rid of the shouldAllow text and urls
